        ITEM_CANNOT_BE_OBTAINED    = 6382; -- You cannot obtain the <item>. Come back after sorting your inventory.
        FULL_INVENTORY_AFTER_TRADE = 6386; -- You cannot obtain the <item>. Try trading again after sorting your inventory.
        ITEM_OBTAINED              = 6388; -- Obtained: <item>.
        GIL_OBTAINED               = 6389; -- Obtained <number> gil.
        KEYITEM_OBTAINED           = 6391; -- Obtained key item: <keyitem>.
        KEYITEM_LOST               = 6392; -- Lost key item: <keyitem>.
        NOT_HAVE_ENOUGH_GIL        = 6393; -- You do not have enough gil.
        ITEMS_OBTAINED             = 6397; -- You obtain <number> <item>!
        ASSAULT_31_START           = 7477; -- Commencing <assault>! Objective: Escort the prisoner
        ASSAULT_32_START           = 7478; -- Commencing <assault>! Objective: Destroy the undead
        ASSAULT_33_START           = 7479; -- Commencing <assault>! Objective: Find the survivors
        ASSAULT_34_START           = 7480; -- Commencing <assault>! Objective: Eliminate the Black Baron
        ASSAULT_35_START           = 7481; -- Commencing <assault>! Objective: Activate the bridge
        ASSAULT_36_START           = 7482; -- Commencing <assault>! Objective: Exterminate the chigoes
        ASSAULT_37_START           = 7483; -- Commencing <assault>! Objective: Clear the mine fields
        ASSAULT_38_START           = 7484; -- Commencing <assault>! Objective: Locate the generals
        ASSAULT_39_START           = 7485; -- Commencing <assault>! Objective: Retrieve the Mark-IIs
        ASSAULT_40_START           = 7486; -- Commencing <assault>! Objective: Assassinate King Goldemar
        TIME_TO_COMPLETE           = 7507; -- You have <number> [minute/minutes] (Earth time) to complete this mission.
        MISSION_FAILED             = 7508; -- The mission has failed. Leaving area.
        RUNE_UNLOCKED_POS          = 7509; -- ission objective completed. Unlocking Rune of Release ([A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y/Z]-#).
        RUNE_UNLOCKED              = 7510; -- ission objective completed. Unlocking Rune of Release.
        ASSAULT_POINTS_OBTAINED    = 7511; -- You gain <number> [Assault point/Assault points]!
        TIME_REMAINING_MINUTES     = 7512; -- ime remaining: <number> [minute/minutes] (Earth time).
        TIME_REMAINING_SECONDS     = 7513; -- ime remaining: <number> [second/seconds] (Earth time).
        PARTY_FALLEN               = 7515; -- ll party members have fallen in battle. Mission failure in <number> [minute/minutes].
        EXCALIACE_START            = 7524; -- Such a lot of trouble for one little corsair... Shall we be on our way?
        EXCALIACE_END1             = 7525; -- Yeah, I got it. Stay here and keep quiet.
        EXCALIACE_END2             = 7526; -- Hey... It was a short trip, but nothing is ever dull around you, huh?
        EXCALIACE_ESCAPE           = 7527; -- Heh. The Immortals really must be having troubles finding troops if they sent this bunch of slowpokes to watch over me...
        EXCALIACE_PAIN1            = 7528; -- Oomph!
        EXCALIACE_PAIN2            = 7529; -- Ouch!
        EXCALIACE_PAIN3            = 7530; -- Youch!
        EXCALIACE_PAIN4            = 7531; -- Damn, that's gonna leave a mark!
        EXCALIACE_PAIN5            = 7532; -- Urggh!
        EXCALIACE_CRAB1            = 7533; -- Over to you.
        EXCALIACE_CRAB2            = 7534; -- What's this guy up to?
        EXCALIACE_CRAB3            = 7535; -- Uh-oh.
        EXCALIACE_DEBAUCHER1       = 7536; -- Wh-what the...!?
        EXCALIACE_DEBAUCHER2       = 7537; -- H-help!!!
        EXCALIACE_RUN              = 7538; -- Now's my chance!
        EXCALIACE_TOO_CLOSE        = 7539; -- Okay, okay, you got me! I promise I won't run again if you step back a bit...please. Someone's been eating too much garlic...
        EXCALIACE_TIRED            = 7540; -- <Pant>...<wheeze>...
        EXCALIACE_CAUGHT           = 7541; -- Damn...
    

